version: "3.9"

volumes:
  tuner-price-fetching-service:
  tuner-web-app:

services:
  tuner-price-fetching-service:
    build: ../price-fetching-service
    restart: always
    environment:
      DISCOGS_API_KEY: YOUR_API_KEY_HERE
      DISCOGS_API_SECRET: YOUR_SECRET_HERE
    volumes:
      - ../price-fetching-service:/home/app
    working_dir: /home/app
    command: sh -c "npm install && npm run start"
    ports:
      - 5000:5000
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  tuner-web-app:
    image: node:16.15-alpine3.14
    restart: always
    volumes:
      - ../web-app:/home/app
    working_dir: /home/app
    ports:
      - 3000:3000
    environment:
      API_URL: "http://localhost:5000"
    depends_on:
      tuner-price-fetching-service:
        condition: service_healthy
    command: sh -c "npm install && npm run start"
